app = "smartcred-webhook"

# Build usando o builder oficial NodeJS do Fly
[build]
  image = "node:18-bullseye"  # imagem oficial Node 18

# Variáveis de ambiente default (pode sobrescrever via Fly UI)
[env]
  PORT = "8080"

# Serviços
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

# Health check opcional
  [services.checks]
    type = "http"
    path = "/"
    interval = 10000
    timeout = 2000
    grace_period = 10000
