# fly.toml otimizado para NodeJS
app = "smartcred-webhook"

# NodeJS puro, usando comando start do package.json
[build]
  image = "node:18-bullseye"  # imagem oficial NodeJS

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
