app = "smartcred-webhook"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "node:18-bullseye"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls","http"]
