app = "smartcred-webhook"

[build]
  # Builder otimizado para Node.js
  builder = "fly/builders:nodejs"

[env]
  PORT = "8080"
  # As variáveis do Google devem ser configuradas como secrets do Fly
  # Não coloque aqui valores sensíveis diretamente
  # GOOGLE_CLIENT_EMAIL = "seu_email"
  # GOOGLE_PRIVATE_KEY = "sua_chave"
  # SPREADSHEET_ID = "id_da_planilha"
  PIXEL_ID = "sua_pixel_id_aqui"
  ACCESS_TOKEN = "seu_access_token_aqui"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
